name: static check
on: ['push']
jobs:
  mypy-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo static check of the sources
      - run: conda info
      - name: checkout repository
        uses: actions/checkout@v4
      - run: ls
      - name: setup conda environement
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          environment-file: conda.yml
          activate-environment: fastapi-web
      - run: pip install -r requirements.dev.txt
      - run: mypy main.py