name: static check
on: ['push']
jobs:
  mypy-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo static check of the sources
      - run: conda info
      - uses: actions/checkout@v4
      - run: ls
      - run: conda env create --file conda.yml --prune